adding .travis.ym + fix for dmg load

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -3,73 +3,78 @@ dist: trusty
 os: linux
 language: minimal
 cache:
+  apt: true
+  ccache: true
   directories:
   - depends/built
   - depends/sdk-sources
-  - $HOME/.ccache
+  - "$HOME/.ccache"
 env:
   global:
-    - MAKEJOBS=-j3
-    - RUN_TESTS=false
-    - CHECK_DOC=0
-    - CHECK_LOGPRINT=0
-    - BOOST_TEST_RANDOM=1$TRAVIS_BUILD_ID
-    - CCACHE_SIZE=100M
-    - CCACHE_TEMPDIR=/tmp/.ccache-temp
-    - CCACHE_COMPRESS=1
-    - BASE_OUTDIR=$TRAVIS_BUILD_DIR/out
-    - SDK_URL=https://bitcoincore.org/depends-sources/sdks
-    - WINEDEBUG=fixme-all
+  - MAKEJOBS=-j5
+  - CCACHE_SIZE=400M
+  - CCACHE_TEMPDIR=/tmp/.ccache-temp
+  - CCACHE_COMPRESS=1
+  - SDK_URL=https://bitcoincore.org/depends-sources/sdks/
+  - LASTTAG=$(git describe --tags)
+  - TAG="$LASTTAG"
   matrix:
-# ARM
-    - HOST=arm-linux-gnueabihf PACKAGES="g++-arm-linux-gnueabihf" CHECK_DOC=1 CHECK_LOGPRINT=1 GOAL="install" BITCOIN_CONFIG="--enable-glibc-back-compat --enable-reduce-exports"
-# Win32
-    - HOST=i686-w64-mingw32 DPKG_ADD_ARCH="i386" DEP_OPTS="NO_QT=1" PACKAGES="python3 nsis g++-mingw-w64-i686 wine1.6 bc" RUN_TESTS=false GOAL="install" BITCOIN_CONFIG="--enable-reduce-exports"
-# 32-bit + dash
-    - HOST=i686-pc-linux-gnu PACKAGES="g++-multilib bc python3-zmq" DEP_OPTS="NO_QT=1" RUN_TESTS=false GOAL="install" BITCOIN_CONFIG="--enable-zmq --enable-glibc-back-compat --enable-reduce-exports LDFLAGS=-static-libstdc++" USE_SHELL="/bin/dash" PYZMQ=true
-# Win64
-    - HOST=x86_64-w64-mingw32 DPKG_ADD_ARCH="i386" DEP_OPTS="NO_QT=1" PACKAGES="python3 nsis g++-mingw-w64-x86-64 wine1.6 bc" RUN_TESTS=false GOAL="install" BITCOIN_CONFIG="--enable-reduce-exports"
-# deviantd
-    - HOST=x86_64-unknown-linux-gnu PACKAGES="bc python3-zmq" DEP_OPTS="NO_QT=1 NO_UPNP=1 DEBUG=1" RUN_TESTS=false GOAL="install" BITCOIN_CONFIG="--enable-zmq --enable-glibc-back-compat --enable-reduce-exports CPPFLAGS=-DDEBUG_LOCKORDER" PYZMQ=true
-# No wallet
-#    - HOST=x86_64-unknown-linux-gnu PACKAGES="python3" DEP_OPTS="NO_WALLET=1" RUN_TESTS=true GOAL="install" BITCOIN_CONFIG="--enable-glibc-back-compat --enable-reduce-exports"
-# Cross-Mac
-    - HOST=x86_64-apple-darwin11 PACKAGES="cmake imagemagick libcap-dev librsvg2-bin libz-dev libbz2-dev libtiff-tools python-dev" BITCOIN_CONFIG="--enable-gui --enable-reduce-exports" OSX_SDK=10.11 GOAL="deploy"
-
+  - HOST=x86_64-apple-darwin14 PACKAGES="cmake imagemagick libcap-dev librsvg2-bin
+    libz-dev libbz2-dev libtiff-tools python-dev zip unzip libc6-dev libc6-dev-amd64"
+    BITCOIN_CONFIG="--enable-gui --enable-reduce-exports --disable-tests --disable-bench --with-bignum=no" OSX_SDK=10.11
+    GOAL="deploy"
 before_install:
-    - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")
+- travis_retry sudo apt-get install python-dev
+- export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" |  sed
+  "s|::|:|g")
 install:
-    - if [ "$PYZMQ" = "true" ]; then pip install pyzmq --user ; fi
-    - if [ -n "$DPKG_ADD_ARCH" ]; then sudo dpkg --add-architecture "$DPKG_ADD_ARCH" ; fi
-    - if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get update; fi
-    - if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get install --no-install-recommends --no-upgrade -qq $PACKAGES; fi
+- if [ -n "$DPKG_ADD_ARCH" ]; then sudo dpkg --add-architecture "$DPKG_ADD_ARCH" ;
+  fi
+- if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get update; fi
+- if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get install --no-install-recommends
+  --no-upgrade -qq $PACKAGES; fi
 before_script:
-    - if [ "$CHECK_DOC" = 1 ]; then contrib/devtools/check-doc.py; fi
-    - if [ "$CHECK_LOGPRINT" = 1 ]; then contrib/devtools/logprint-scanner.py; fi
-    - unset CC; unset CXX
-    - mkdir -p depends/SDKs depends/sdk-sources
-    - if [ -n "$OSX_SDK" -a ! -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then curl --location --fail $SDK_URL/MacOSX${OSX_SDK}.sdk.tar.gz -o depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz; fi
-    - if [ -n "$OSX_SDK" -a -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then tar -C depends/SDKs -xf depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz; fi
-    - make $MAKEJOBS -C depends HOST=$HOST $DEP_OPTS
+- unset CC; unset CXX
+- mkdir -p depends/SDKs depends/sdk-sources
+- if [ -n "$OSX_SDK" -a ! -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then
+  curl --location --fail $SDK_URL/MacOSX${OSX_SDK}.sdk.tar.gz -o depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz;
+  fi
+- if [ -n "$OSX_SDK" -a -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then
+  tar -C depends/SDKs -xf depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz; fi
 script:
-    - export TRAVIS_COMMIT_LOG=`git log --format=fuller -1`
-    - if [ -n "$USE_SHELL" ]; then export CONFIG_SHELL="$USE_SHELL"; fi
-    - OUTDIR=$BASE_OUTDIR/$TRAVIS_PULL_REQUEST/$TRAVIS_JOB_NUMBER-$HOST
-    - BITCOIN_CONFIG_ALL="--disable-dependency-tracking --prefix=$TRAVIS_BUILD_DIR/depends/$HOST --bindir=$OUTDIR/bin --libdir=$OUTDIR/lib"
-    - depends/$HOST/native/bin/ccache --max-size=$CCACHE_SIZE
-    - test -n "$USE_SHELL" && eval '"$USE_SHELL" -c "./autogen.sh"' || ./autogen.sh
-    - ./configure --cache-file=config.cache $BITCOIN_CONFIG_ALL $BITCOIN_CONFIG || ( cat config.log && false)
-    - make distdir PACKAGE=bitcoin VERSION=$HOST
-    - cd bitcoin-$HOST
-    - ./configure --cache-file=../config.cache $BITCOIN_CONFIG_ALL $BITCOIN_CONFIG || ( cat config.log && false)
-    - make $MAKEJOBS $GOAL || ( echo "Build failure. Verbose build follows." && make $GOAL V=1 ; false )
-    - export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/depends/$HOST/lib
-    - if [ "$RUN_TESTS" = "true" ]; then travis_wait 30 make $MAKEJOBS check VERBOSE=1; fi
-    #- if [ "$RUN_TESTS" = "true" ]; then qa/pull-tester/rpc-tests.py --coverage; fi
-after_script:
-    - echo $TRAVIS_COMMIT_RANGE
-    - echo $TRAVIS_COMMIT_LOG
-#notifications:
-  #slack:
-    #secure: 
-        
+- cd $TRAVIS_BUILD_DIR/depends
+- make $MAKEJOBS HOST=$HOST $DEP_OPTS
+- cd $TRAVIS_BUILD_DIR
+- "./autogen.sh"
+- CONFIG_SITE=$TRAVIS_BUILD_DIR/depends/$HOST/share/config.site ./configure $BITCOIN_CONFIG_ALL
+  $BITCOIN_CONFIG --prefix=$TRAVIS_BUILD_DIR/../graphcoin-$HOST-$TAG
+- make $MAKEJOBS $GOAL || ( echo "Build failure. Verbose build follows." && make $GOAL
+  V=1 ; false )
+before_deploy:
+- if [ "$HOST" == "x86_64-apple-darwin14" ]; then mv Graphcoin-Core.dmg Graphcoin-Core-$TAG-macosx-generic.dmg;
+  FILE=Graphcoin-Core-$TAG-macosx-generic.dmg; fi
+- if [ "$HOST" == "x86_64-w64-mingw32" ]; then cd $TRAVIS_BUILD_DIR/../; zip -r graphcoin-$TAG-win-x64.zip
+  graphcoin-$HOST-$TAG; mv graphcoin-$TAG-win-x64.zip $TRAVIS_BUILD_DIR/; cd $TRAVIS_BUILD_DIR;
+  FILE="graphcoin-$TAG-win-x64.zip"; fi
+- if [ "$HOST" == "i686-w64-mingw32" ]; then cd $TRAVIS_BUILD_DIR/../; zip -r graphcoin-$TAG-win-x32.zip
+  graphcoin-$HOST-$TAG; mv graphcoin-$TAG-win-x32.zip $TRAVIS_BUILD_DIR/; cd $TRAVIS_BUILD_DIR;
+  FILE="graphcoin-$TAG-win-x32.zip"; fi
+- if [ "$HOST" == "i686-pc-linux-gnu" ]; then cd $TRAVIS_BUILD_DIR/../; zip -r graphcoin-$TAG-$HOST.zip
+  graphcoin-$HOST-$TAG; mv graphcoin-$TAG-$HOST.zip $TRAVIS_BUILD_DIR/; cd $TRAVIS_BUILD_DIR;
+  FILE="graphcoin-$TAG-$HOST.zip"; fi
+- if [ "$HOST" == "x86_64-pc-linux-gnu" ]; then cd $TRAVIS_BUILD_DIR/../; zip -r graphcoin-$TAG-$HOST.zip
+  graphcoin-$HOST-$TAG; mv graphcoin-$TAG-$HOST.zip $TRAVIS_BUILD_DIR/; cd $TRAVIS_BUILD_DIR;
+  FILE="graphcoin-$TAG-$HOST.zip"; fi
+- if [ "$HOST" == "arm-linux-gnueabihf" ]; then cd $TRAVIS_BUILD_DIR/../; zip -r graphcoin-$TAG-$HOST.zip
+  graphcoin-$HOST-$TAG; mv graphcoin-$TAG-$HOST.zip $TRAVIS_BUILD_DIR/; cd $TRAVIS_BUILD_DIR;
+  FILE="graphcoin-$TAG-$HOST.zip"; fi
+deploy:
+  provider: releases
+  api_key:
+    secure: W1pvF1NheypxqdJF42HijuFPonwOIoRmTMlFTWitchdOqdC28II8iCDo9+b8j6wdUYccND98GO+l1gqaLYbqF7LD32UZBKNbn7CKci3hOsxB/dYexZmDCfd1rabe4rdC/BDwIP+KJhYAIZUHGWLRo3m2D6KdK1Cq3NAIvWogPWqiHWf+3peCT2jTpOUus7EGKc44Z3xHBeZbRkhrz5axT6sJ36gR4tyGYE/r6bTEjbFJJ/uV683+7Ci2vO1VhshUxsR3gbruturhFZXgxWPIsSuyUaayMMyVFVvkJNYH7xMeeB7FX+u2YG4luKgK/N8rhRj7bSdkhi3wpdQadlCRLtx5u8BLaBKffDhcg0LFTvCWwPSd90AJLSx4ynHnbWJmcCh3yeOV0mTQ+RkyzLr8R7V5g4EsR449xB4HcZIPtE3MNOAq9vX1KAQ2yzGF6ckhF1x0UI1yiZgAyFhhXjMptayktFbxVDj87jPi97srOSTU4YHZ67letNo9aTC49X/rSVf9rM9sn2ns4OrIGKUwkYJkdSGF3HA6BvJyd6VCUuwKxmm+s8EVHMpCHRcCQ7g8YXACxXQi9g/HrZKh52E8mRRw7rQ2HTF8DZ2xg7QS48Yv1mnY7Ykdr/mgliVIJqPXsr0MdyXMG7TtqGgNAJJ4Fp+l8HY/k6qcI4fgSDPAIB4=
+  file: "$FILE"
+  on:
+    repo: ScaMar/source-1
+    branch: master
+    tags: true
+  skip_cleanup: true
